"use client";
import { useEffect, useState } from "react";
import { ArrowUpRight, ArrowRight, ArrowDownToLine, Bell, Boxes, Check, ChevronRight, CircleHelp, LayoutGrid, LoaderCircle, Network, Package, RefreshCw, Search, Send, Settings2, ShieldCheck, Sparkles, TriangleAlert, X, Zap } from "lucide-react";
import { Sidebar, SidebarProvider, SidebarHeader, SidebarContent, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger } from "@/components/ui/sidebar";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { STORES, DEFAULT_RULE, stockLevel, recommendations, searchProducts, type Product, type Rule, type StoreId } from "@/lib/inventory";

type Connection={id:StoreId;connected:boolean;source?:"environment";lastSync?:string;error?:string};
type Message={role:"user"|"assistant";text:string;products?:Product[]};
const nav=[{id:"overview",label:"Visão geral",icon:LayoutGrid},{id:"inventory",label:"Consulta de estoque",icon:Boxes},{id:"replenish",label:"Reposição",icon:Package},{id:"automations",label:"Automações",icon:Zap},{id:"agent",label:"Agente de estoque",icon:Sparkles},{id:"connections",label:"Conexões",icon:Network}];
function stamp(date?:string){return date?new Date(date).toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}):"Ainda não sincronizada";}
export default function Home(){
  const [view,setView]=useState("overview"),[demo,setDemo]=useState(false),[products,setProducts]=useState<Product[]>([]);
  const [rule,setRule]=useState<Rule>(DEFAULT_RULE),[draft,setDraft]=useState<Rule>(DEFAULT_RULE),[connections,setConnections]=useState<Connection[]>([]);
  const stores=STORES.filter(s=>connections.some(c=>c.id===s.id));
  const [query,setQuery]=useState(""),[storeFilter,setStoreFilter]=useState("all"),[statusFilter,setStatusFilter]=useState("all");
  const [busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[ready,setReady]=useState(false);
  const [detail,setDetail]=useState<Product|null>(null),[message,setMessage]=useState(""),[messages,setMessages]=useState<Message[]>([]),[chatBusy,setChatBusy]=useState(false);
  async function load(){
    try{const r=await fetch("/api/inventory",{cache:"no-store"});if(!r.ok)throw Error("Não foi possível carregar as conexões. Tente novamente.");const d=await r.json() as {connections:Connection[];rule:Rule;demo:boolean;products:Product[]};setConnections(d.connections);setRule(d.rule);setDraft(d.rule);setDemo(d.demo);setProducts(d.products);}
    catch(e){setNotice((e as Error).message);}finally{setReady(true);}
  }
  useEffect(()=>{void load();},[]);
  useEffect(()=>{if(storeFilter!=="all"&&!connections.some(c=>c.id===storeFilter))setStoreFilter("all");},[connections,storeFilter]);
  useEffect(()=>{if(ready&&!demo&&connections.some(c=>c.connected&&!c.lastSync&&!c.error))void sync();},[ready,demo]);
  useEffect(()=>{if(!ready||demo||!rule.enabled)return;const timer=setInterval(()=>void sync(true),rule.interval*60000);return()=>clearInterval(timer);},[ready,demo,rule.enabled,rule.interval]);
  useEffect(()=>{
    const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;
    if(!context)return;const lifecycle=new AbortController();
    Promise.resolve(context.registerTool({name:"consultar_estoque",description:"Consulta o último estoque registrado por produto ou SKU nas lojas configuradas. Retorna a origem e a data dos dados.",inputSchema:{type:"object",properties:{produto:{type:"string",minLength:1,maxLength:200}},required:["produto"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:unknown)=>{const p=(input as {produto?:unknown})?.produto;if(typeof p!=="string"||!p.trim()||p.length>200)throw Error("Informe um nome ou SKU válido.");const r=await fetch("/api/agent",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:p})});if(!r.ok)throw Error("Consulta indisponível");return r.json();}},{signal:lifecycle.signal})).catch(()=>{});
    return()=>lifecycle.abort();
  },[]);
  async function sync(automatic=false){
    if(busy)return;if(demo){if(!automatic){setView("connections");setNotice("Configure uma loja no arquivo local de ambiente para consultar o estoque real.");}return;}
    setBusy(true);try{const r=await fetch("/api/sync",{method:"POST"});const d=await r.json() as {error?:string;message:string};await load();if(!r.ok)throw Error(d.error||d.message||"Falha na sincronização.");if(!automatic)setNotice(d.message);}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}
  }
  async function saveRule(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch("/api/rules",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});const d=await r.json() as {error:string;rule:Rule};if(!r.ok)throw Error(d.error);setRule(d.rule);setNotice("Regras salvas. Os alertas serão recalculados em cada sincronização.");}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
  async function ask(text=message){
    if(!text.trim()||chatBusy)return;setMessage("");setMessages(m=>[...m,{role:"user",text}]);setChatBusy(true);
    try{const r=await fetch("/api/agent",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text})});const d=await r.json() as {error:string;text:string;demo:boolean;products:Product[]};if(!r.ok)throw Error(d.error);setMessages(m=>[...m,{role:"assistant",text:(d.demo?"Demonstração · ":"")+d.text,products:d.products}]);}
    catch(e){setMessages(m=>[...m,{role:"assistant",text:"Não foi possível consultar: "+(e as Error).message}]);}finally{setChatBusy(false);}
  }
  const recs=recommendations(products,rule),out=recs.filter(r=>r.stock.quantity!<=0).length;
  const quantities=products.flatMap(p=>p.stocks).filter(s=>s.quantity!==null&&!s.shared);
  const total=quantities.reduce((a,s)=>a+Math.max(0,s.quantity!),0);
  const filtered=searchProducts(products,query).filter(p=>p.stocks.some(s=>(storeFilter==="all"||s.storeId===storeFilter)&&(statusFilter==="all"||(statusFilter==="attention"?["low","out"].includes(stockLevel(s,rule)):stockLevel(s,rule)===statusFilter))));
  function exportCSV(){const rows=[["Produto","SKU","Loja","Estoque","Mínimo","Reposição sugerida","Origem"],...recs.map(r=>[r.product.name,r.product.sku,stores.find(s=>s.id===r.stock.storeId)!.name,r.stock.quantity,rule.minimum,r.quantity,demo?"Demonstração":"WooCommerce"])];const safe=(v:unknown)=>{let s=String(v??"");if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const blob=new Blob(["\ufeff"+rows.map(r=>r.map(safe).join(";")).join("\r\n")],{type:"text/csv;charset=utf-8;"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="reposicao-"+(demo?"demonstracao":"estoque")+".csv";a.click();URL.revokeObjectURL(a.href);}
  function ProductTable({items}:{items:Product[]}){return <Table className="stock-table"><TableHeader><TableRow><TableHead>Produto / SKU</TableHead>{stores.map(s=><TableHead key={s.id}><span className="store-dot" style={{background:s.color}}/>{s.short}</TableHead>)}<TableHead>Total conhecido</TableHead><TableHead/></TableRow></TableHeader><TableBody>{items.map(p=><TableRow key={p.key}><TableCell><button className="product-name" onClick={()=>setDetail(p)}><span className="product-symbol"><Package size={19}/></span><span><strong>{p.name}</strong><small>{p.sku||"Sem SKU · não agrupado"}</small></span></button></TableCell>{stores.map(s=>{const stock=p.stocks.find(x=>x.storeId===s.id);return <TableCell key={s.id}><span className={"stock-number "+(stock?stockLevel(stock,rule):"unknown")}>{!stock?"—":stock.quantity===null?"N/D":stock.quantity}{stock&&["low","out"].includes(stockLevel(stock,rule))&&<span className="mini-dot"/>}</span>{stock?.shared&&<small>Compartilhado</small>}</TableCell>;})}<TableCell className="total-number">{p.stocks.some(s=>s.quantity!==null&&!s.shared)?p.stocks.reduce((n,s)=>n+(s.shared?0:Math.max(0,s.quantity??0)),0):"—"}</TableCell><TableCell><button aria-label={"Ver "+p.name} className="icon-button" onClick={()=>setDetail(p)}><ChevronRight size={17}/></button></TableCell></TableRow>)}</TableBody></Table>;}
  function Empty(){return <div className="empty"><Search size={30}/><h3>Nenhum produto encontrado</h3><p>Altere os filtros ou sincronize uma loja conectada.</p></div>;}
  const title=nav.find(n=>n.id===view)?.label||"Visão geral";
  return <SidebarProvider style={{"--sidebar-width":"238px"} as React.CSSProperties}>
    <Sidebar className="app-sidebar"><SidebarHeader><a className="brand" href="/"><span className="brand-mark"><Network size={24}/></span><span>elo<span className="brand-period">.</span></span></a><div className="workspace-label">WHOLESALE WORKSPACE</div></SidebarHeader><SidebarContent><SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>setView(n.id)} className="nav-button"><n.icon size={19}/><span>{n.label}</span>{n.id==="replenish"&&<b className="nav-count">{recs.length}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="side-stores"><span className="eyebrow">SUAS LOJAS</span>{stores.map(s=><button key={s.id} onClick={()=>{setView("inventory");setStoreFilter(s.id);}}><span className="store-dot" style={{background:s.color}}/>{s.name}<span className="connection-dot" title={connections.find(c=>c.id===s.id)?.connected?"Conectada":"Aguardando conexão"}/></button>)}</div></SidebarContent><SidebarFooter><div className="privacy"><ShieldCheck size={17}/><span>Workspace privado</span></div><div className="profile"><span className="avatar">W</span><div><strong>Gestão wholesale</strong><small>{stores.length} {stores.length===1?"loja":"lojas"} · um só lugar</small></div></div></SidebarFooter></Sidebar>
    <div className="workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-menu"/><span>Workspace</span><ChevronRight size={14}/><strong>{title}</strong></div><div className="topbar-right"><span className={"mode-badge "+(demo?"demo":"live")}><span/>{demo?"Demonstração":"Dados das lojas"}</span><button className="icon-button" onClick={()=>{setView("inventory");setStatusFilter("attention");}} aria-label="Ver alertas"><Bell size={19}/>{recs.length>0&&<i/>}</button></div></header>
    <main><div className="page-heading"><div><div className="eyebrow">CONTROLE DE ESTOQUE</div><h1>{view==="overview"?"Tudo conectado. Sob controle.":title}</h1><p>{view==="overview"?"O estoque das suas lojas, lado a lado.":view==="inventory"?"Encontre um produto e compare a disponibilidade em cada loja.":view==="replenish"?"Priorize o que falta e prepare a próxima reposição.":view==="automations"?"Defina quando um produto precisa de atenção.":view==="connections"?"Status das conexões configuradas no arquivo local de ambiente.":"Pergunte por um produto, uma loja ou uma necessidade de reposição."}</p></div>{view!=="agent"&&<button className="button primary" disabled={busy} onClick={()=>sync()}><RefreshCw size={16} className={busy?"spin":""}/>{busy?"Sincronizando…":"Sincronizar estoques"}</button>}</div>
    {notice&&<div className="notice" role="status"><CircleHelp size={18}/><span>{notice}</span><button aria-label="Fechar aviso" onClick={()=>setNotice("")}><X size={16}/></button></div>}
    {demo&&<div className="demo-banner"><span><span className="demo-indicator"/>Você está explorando dados de exemplo. Configure o arquivo local para ver o estoque real.</span><button onClick={()=>setView("connections")}>Ver conexões <ArrowRight size={15}/></button></div>}
    {ready&&!stores.length&&<div className="notice" role="status"><Network size={18}/><span>Nenhuma loja configurada. Adicione as credenciais ao .env.local e reinicie o servidor local.</span></div>}
    {!demo&&connections.some(c=>!c.connected||c.error||!c.lastSync)&&<div className="demo-banner"><span><TriangleAlert size={17}/>Há lojas sem conexão, sem sincronização ou com erro. Os dados exibidos podem estar incompletos ou desatualizados.</span><button onClick={()=>setView("connections")}>Ver conexões <ArrowRight size={15}/></button></div>}{(view==="overview"||view==="inventory")&&<>
    {view==="overview"&&<><div className="metrics"><article><span>Unidades em estoque <Boxes size={17}/></span><strong>{total.toLocaleString("pt-BR")}</strong><small>Quantidades conhecidas nas lojas configuradas</small></article><article><span>Produtos no catálogo <Package size={17}/></span><strong>{products.length}</strong><small>Agrupados por SKU idêntico</small></article><article className="metric-alert"><span>Estoque baixo <TriangleAlert size={17}/></span><strong>{recs.length-out}<em>posições</em></strong><small>Até {rule.minimum} unidades por loja</small></article><article className="metric-out"><span>Sem estoque <span className="mini-dot"/></span><strong>{out}<em>posições</em></strong><small>Reposição prioritária</small></article></div>
    <div className="store-overview" style={{gridTemplateColumns:"repeat("+Math.max(stores.length,1)+", minmax(0, 1fr))"}}>{stores.map(s=>{const c=connections.find(x=>x.id===s.id);const units=products.flatMap(p=>p.stocks).filter(x=>x.storeId===s.id&&x.quantity!==null&&!x.shared).reduce((n,x)=>n+Math.max(0,x.quantity!),0);return <button key={s.id} className="store-summary" onClick={()=>{setView("inventory");setStoreFilter(s.id);}}><span className="store-logo" style={{color:s.color,background:s.color+"13"}}>{s.initials}</span><div><strong>{s.name}</strong><small>{demo?"Estoque de demonstração":c?.error?"Falha na última sincronização":stamp(c?.lastSync)}</small></div><div className="store-units"><strong>{units}</strong><small>unidades</small></div><ChevronRight size={16}/></button>;})}</div></>}
    <div className={view==="overview"?"overview-grid":""}><section className="panel inventory-panel"><div className="panel-heading"><div><h2>Estoque por produto <span className="count">{filtered.length}</span></h2><p>Uma visão consolidada das lojas configuradas.</p></div>{view==="overview"&&<button className="text-button" onClick={()=>setView("inventory")}>Ver todos <ArrowUpRight size={16}/></button>}</div><div className="filters"><div className="search-field"><Search size={17}/><input aria-label="Buscar produto ou SKU" placeholder="Buscar produto ou SKU…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Limpar busca" onClick={()=>setQuery("")}><X size={14}/></button>}</div><Select value={storeFilter} onValueChange={v=>setStoreFilter(v??"all")}><SelectTrigger aria-label="Filtrar loja"><SelectValue>{storeFilter==="all"?"Todas as lojas":stores.find(s=>s.id===storeFilter)?.short}</SelectValue></SelectTrigger><SelectContent><SelectItem value="all">Todas as lojas</SelectItem>{stores.map(s=><SelectItem value={s.id} key={s.id}>{s.name}</SelectItem>)}</SelectContent></Select><Select value={statusFilter} onValueChange={v=>setStatusFilter(v??"all")}><SelectTrigger aria-label="Filtrar situação"><SelectValue>{{all:"Todas as situações",attention:"Precisa de atenção",low:"Estoque baixo",out:"Sem estoque",unknown:"Não informado"}[statusFilter]}</SelectValue></SelectTrigger><SelectContent>{Object.entries({all:"Todas as situações",attention:"Precisa de atenção",low:"Estoque baixo",out:"Sem estoque",unknown:"Não informado"}).map(([v,l])=><SelectItem value={v} key={v}>{l}</SelectItem>)}</SelectContent></Select></div>{filtered.length?<ProductTable items={view==="overview"?filtered.slice(0,6):filtered}/>:<Empty/>}<div className="table-footer"><span><i className="legend-dot amber"/>Estoque baixo <i className="legend-dot red"/>Sem estoque</span><span>N/D: não controlado · —: não encontrado</span></div></section>
    {view==="overview"&&<aside className="insights"><section className="agent-teaser"><span className="agent-icon"><Sparkles size={23}/></span><div className="eyebrow">SEU AGENTE DE ESTOQUE</div><h2>Menos buscas.<br/>Mais respostas.</h2><p>“Veja para mim o estoque de Tsunu em cada loja.”</p><button onClick={()=>{setView("agent");void ask("Veja para mim o estoque de Tsunu em cada loja");}}>Perguntar ao agente <ArrowUpRight size={18}/></button></section><section className="panel attention"><div className="panel-heading"><h2>Próximas reposições</h2><span className="alert-icon"><TriangleAlert size={17}/></span></div>{recs.slice(0,3).map((r,i)=><button className="attention-row" key={i} onClick={()=>setDetail(r.product)}><span><strong>{r.product.name}</strong><small>{stores.find(s=>s.id===r.stock.storeId)?.name}</small></span><b>+{r.quantity}<small>unidades</small></b></button>)}{!recs.length&&<p className="panel-pad">Nenhuma reposição necessária.</p>}<button className="attention-link" onClick={()=>setView("replenish")}>Ver sugestões de reposição <ArrowRight size={15}/></button></section></aside>}</div></>}
    {view==="replenish"&&<section className="panel"><div className="panel-heading"><div><h2>{recs.length} posições para repor</h2><p>Reposição até {rule.target} unidades por loja. Estimativa por nível mínimo; não é uma previsão de demanda.</p></div><button className="button" onClick={exportCSV} disabled={!recs.length}><ArrowDownToLine size={16}/>Exportar CSV</button></div>{recs.length?<Table className="stock-table"><TableHeader><TableRow>{["Produto","Loja","Disponível","Mínimo","Sugestão"].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{recs.map(r=><TableRow key={r.product.key+r.stock.storeId}><TableCell><button className="product-name" onClick={()=>setDetail(r.product)}><span><strong>{r.product.name}</strong><small>{r.product.sku||"Sem SKU"}</small></span></button></TableCell><TableCell>{stores.find(s=>s.id===r.stock.storeId)?.name}</TableCell><TableCell><span className={"stock-number "+stockLevel(r.stock,rule)}>{r.stock.quantity}</span></TableCell><TableCell>{rule.minimum}</TableCell><TableCell><b className="suggestion">+{r.quantity} un.</b></TableCell></TableRow>)}</TableBody></Table>:<Empty/>}<div className="table-footer">As sugestões não geram compras nem alteram o estoque das lojas.</div></section>}
    {view==="automations"&&<div className="settings-grid"><form className="panel settings-panel" onSubmit={saveRule}><span className="settings-icon"><Settings2 size={24}/></span><h2>Regra de estoque baixo</h2><p>Aplicada a cada produto com quantidade controlada, em cada loja.</p><label className="switch-row"><span><strong>Monitoramento no painel</strong><small>Sincronizar automaticamente enquanto esta página estiver aberta.</small></span><Switch checked={draft.enabled} onCheckedChange={v=>setDraft({...draft,enabled:v})}/></label><div className="form-row"><label>Estoque mínimo<input type="number" min="0" max="99999" required value={draft.minimum} onChange={e=>setDraft({...draft,minimum:Number(e.target.value)})}/><small>Alertar quando o estoque for menor ou igual.</small></label><label>Estoque desejado<input type="number" min={draft.minimum+1} max="100000" required value={draft.target} onChange={e=>setDraft({...draft,target:Number(e.target.value)})}/><small>Quantidade a atingir na reposição.</small></label></div><label>Intervalo de atualização<Select value={String(draft.interval)} onValueChange={v=>setDraft({...draft,interval:Number(v)})}><SelectTrigger><SelectValue>{draft.interval} minutos</SelectValue></SelectTrigger><SelectContent>{[5,15,30,60].map(n=><SelectItem key={n} value={String(n)}>{n} minutos</SelectItem>)}</SelectContent></Select></label><button className="button primary" disabled={busy||!ready} type="submit"><Check size={16}/>Salvar regra</button></form><div><section className="panel settings-panel"><Zap size={25}/><h2>O que acontece automaticamente</h2><ol><li>O painel consulta as lojas conectadas.</li><li>Compara cada quantidade com o estoque mínimo.</li><li>Atualiza os alertas e a lista de reposição.</li></ol><div className="info-block">Com a página fechada, a atualização depende de um agendador externo. As instruções estão no projeto; esse agendamento ainda não está ativado.</div></section><section className="formula"><span className="eyebrow">COMO A SUGESTÃO É CALCULADA</span><p>Estoque desejado − estoque disponível</p><small>Exemplo: {draft.target} − 8 = {Math.max(0,draft.target-8)} unidades para repor.</small></section></div></div>}
    {view==="connections"&&<><div className="connection-grid" style={{gridTemplateColumns:"repeat("+Math.max(stores.length,1)+", minmax(0, 1fr))"}}>{stores.map(s=>{const c=connections.find(x=>x.id===s.id);return <section className="panel connection-card" key={s.id}><div className="connection-top"><span className="store-logo" style={{color:s.color,background:s.color+"13"}}>{s.initials}</span><span className={"pill "+(c?.error?"neutral":c?.lastSync?"green":"neutral")}>{c?.error?"Erro na conexão":c?.lastSync?"Conectada":"Aguardando consulta"}</span></div><h2>{s.name}</h2><p className="host">{s.host}</p><div className="connection-meta"><span>Plataforma<strong>WordPress + WooCommerce</strong></span><span>Credenciais<strong>{c?.connected?".env.local":"Não configuradas"}</strong></span><span>Última atualização<strong>{stamp(c?.lastSync)}</strong></span></div>{c?.error&&<p className="connection-error">{c.error}</p>}<div className="connection-source"><ShieldCheck size={16}/>{c?.connected?"Configurada no arquivo local":"Sem credenciais no arquivo local"}</div></section>;})}</div><section className="panel connection-help"><ShieldCheck size={27}/><div><h2>Credenciais gerenciadas pelo arquivo local</h2><p>As conexões são lidas do <strong>.env.local</strong> no servidor local. Este painel mostra apenas o status das lojas. Para alterar uma conexão, atualize o arquivo e reinicie o servidor. As chaves não são cadastradas nem exibidas aqui.</p></div></section></>}
    {view==="agent"&&<section className="panel chat-panel"><div className="chat-header"><span className="agent-icon"><Sparkles size={22}/></span><div><h2>Agente Elo</h2><p>Consulta de estoque por nome ou SKU · respostas baseadas no último registro</p></div><span className="pill green">Consultas guiadas</span></div><div className="chat-messages" aria-live="polite">{!messages.length?<div className="chat-welcome"><Sparkles size={37}/><h2>O que vamos consultar?</h2><p>Encontre disponibilidade nas lojas configuradas ou veja o que precisa de reposição.</p><div className="prompts">{["Estoque de Tsunu","Quais produtos estão com estoque baixo?","Sugestão de reposição na Maya","Quais produtos estão zerados?"].map(p=><button key={p} onClick={()=>ask(p)}>{p}<ArrowUpRight size={15}/></button>)}</div></div>:messages.map((m,i)=><div className={"message "+m.role} key={i}><span className="message-author">{m.role==="user"?"Você":"Agente Elo"}</span><p>{m.text}</p>{m.products?.length?<div className="chat-results"><ProductTable items={m.products}/></div>:null}</div>)}{chatBusy&&<div className="thinking"><LoaderCircle className="spin" size={18}/>Consultando o estoque…</div>}</div><form className="chat-form" onSubmit={e=>{e.preventDefault();void ask();}}><input aria-label="Pergunta ao agente" value={message} maxLength={500} onChange={e=>setMessage(e.target.value)} placeholder="Ex.: veja o estoque de Rapé Tsunu nas três lojas"/><button className="button primary" aria-label="Enviar pergunta" disabled={chatBusy||!message.trim()}><Send size={19}/></button></form><div className="chat-footnote">Consulta guiada de estoque. Produtos não encontrados e quantidades desconhecidas são indicados nas respostas.</div></section>}
    <footer className="page-footer"><span><Network size={14}/> elo. <span>Estoque conectado</span></span><span>{demo?"Nenhuma loja configurada":"Fonte: API WooCommerce · quantidades da última sincronização"}</span></footer></main></div>
    <Sheet open={!!detail} onOpenChange={open=>{if(!open)setDetail(null);}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>{detail?.name}</SheetTitle><SheetDescription>{detail?.sku||"Produto sem SKU"}</SheetDescription></SheetHeader>{detail&&<div className="detail-body"><span className="pill neutral">{detail.category}</span>{stores.map(s=>{const stock=detail.stocks.find(x=>x.storeId===s.id);return <div className="detail-stock" key={s.id}><span className="store-dot" style={{background:s.color}}/><div><strong>{s.name}</strong><small>{demo?"Demonstração":stamp(stock?.updatedAt)}</small></div><b>{!stock?"—":stock.quantity===null?"N/D":stock.quantity}</b></div>;})}<div className="info-block">A correspondência entre lojas usa o SKU exato. Quantidades compartilhadas pelo produto pai não são somadas duas vezes. Produtos sem quantidade controlada não geram sugestões.</div><button className="button primary" onClick={()=>{setDetail(null);setView("agent");void ask(detail.sku||detail.name);}}>Consultar com o agente <Sparkles size={17}/></button></div>}</SheetContent></Sheet>

  </SidebarProvider>;
}
