"use client";
import {useEffect,useState,useRef,useMemo} from 'react';
import {STORES,type StoreId} from '@/lib/inventory';
import {filterReplenishmentReport,type ReplenishmentReport} from '@/lib/replenishment';
export function Replenishment({storeIds}:{storeIds:StoreId[]}){
 const [storeId,setStoreId]=useState<StoreId>('sacred');const sequence=useRef(0);
 const [selectedCategories,setSelectedCategories]=useState<string[]>([]);
 const company=STORES.find(s=>s.id===storeId)!.short;
 const [report,setReport]=useState<ReplenishmentReport|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[exporting,setExporting]=useState(false),[view,setView]=useState<'order'|'review'|'all'>('order');
 async function load(){const request=++sequence.current;setBusy(true);setError('');setReport(null);try{const r=await fetch('/api/replenishment?storeId='+storeId,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);if(request===sequence.current)setReport(d);}catch(e){if(request===sequence.current)setError((e as Error).message);}finally{if(request===sequence.current)setBusy(false);}}
 useEffect(()=>{setView('order');void load();return()=>{sequence.current++;};},[storeId]);
 const categories=useMemo(()=>[...new Set(report?.lines.flatMap(line=>line.categories??[])??[])].sort((a,b)=>a.localeCompare(b,'pt-BR')),[report]);
 const filteredReport=report?filterReplenishmentReport(report,selectedCategories):null;
 const order=filteredReport?.lines.filter(r=>r.status==='order')??[],review=filteredReport?.lines.filter(r=>r.status==='review')??[];
 const lines=view==='order'?order:view==='review'?review:filteredReport?.lines??[];
 async function save(format:'pdf'|'xlsx'){if(!filteredReport)return;setExporting(true);try{const {exportReplenishment}=await import('@/lib/replenishment-export');await exportReplenishment(filteredReport,format);}catch{setError('Não foi possível exportar. Tente novamente.');}finally{setExporting(false);}}
 return <section className="replenishment-view"><header><div className="eyebrow">POR EMPRESA</div><h1>Reposição de Estoque</h1><p>Pedido calculado com os mínimos e o estoque da empresa selecionada.</p></header><label className="replenishment-company">Empresa<select value={storeId} disabled={exporting} onChange={event=>{setReport(null);setError('');setSelectedCategories([]);setStoreId(event.target.value as StoreId);}}>{STORES.filter(s=>s.id==='sacred'||storeIds.includes(s.id)).map(s=><option key={s.id} value={s.id}>{s.short}</option>)}</select></label>
 {report&&report.configured!==false&&<div className="category-filter"><label htmlFor="replenishment-category">Categorias · {company}</label><select id="replenishment-category" aria-label="Adicionar categoria na reposição" value="" disabled={busy||exporting||!categories.some(c=>!selectedCategories.includes(c))} onChange={e=>{if(e.target.value)setSelectedCategories(current=>[...current,e.target.value]);}}><option value="">{selectedCategories.length?'Adicionar outra categoria…':'Todas as categorias · selecione para filtrar'}</option>{categories.filter(c=>!selectedCategories.includes(c)).map(name=><option key={name} value={name}>{name}</option>)}</select>{selectedCategories.length>0&&<><div className="category-chips">{selectedCategories.map(name=><button type="button" key={name} disabled={busy||exporting} aria-label={'Remover categoria '+name} onClick={()=>setSelectedCategories(current=>current.filter(c=>c!==name))}>{name} ×</button>)}</div><button type="button" className="category-clear" disabled={busy||exporting} onClick={()=>setSelectedCategories([])}>Limpar categorias</button></>}<small>{categories.length?'Inclui produtos de qualquer categoria selecionada. O filtro também vale para PDF e Excel.':'Nenhuma categoria disponível nos itens com mínimo cadastrado.'}</small></div>}
 <div className="replenishment-actions"><button onClick={()=>void load()} disabled={busy||exporting}>{busy?'Calculando…':'Recalcular pedido'}</button><button onClick={()=>void save('pdf')} disabled={!order.length||busy||exporting}>Exportar PDF</button><button onClick={()=>void save('xlsx')} disabled={!order.length||busy||exporting}>Exportar Excel</button></div>
 {error&&<p role="alert" className="connection-error">{error}</p>}
 {report?.configured===false&&<p className="notice">Ainda não há mínimos cadastrados para {company}. Os mínimos da Sacred são exclusivos dela.</p>}
 {report&&report.configured!==false&&<><p className="table-note">Estoque {company}: {report.lastSync?new Date(report.lastSync).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Não disponível'} (Brasília). Base: {report.source}.</p>{report.warning&&<p role="alert" className="notice">{report.warning}</p>}
 <div className="replenishment-summary"><span><strong>{order.length}</strong> SKUs para repor</span><span><strong>{order.reduce((n,r)=>n+r.order!,0).toLocaleString('pt-BR')}</strong> unidades</span><span><strong>{order.reduce((n,r)=>n+(r.kg??0),0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:6})}</strong> kg{order.some(r=>r.kg===null)?' (parcial)':''}</span><span><strong>{review.length}</strong> para revisão</span></div>
 <p className="table-note">Repor = mínimo − disponível. Saldos negativos contam como zero. Itens sem saldo confiável ficam para revisão e não entram no pedido. Os arquivos incluem o pedido das categorias selecionadas, independentemente da visualização abaixo.</p>
 <div className="replenishment-actions" aria-label="Visualização da reposição">{([['order','Pedido'],['review','Para revisão'],['all','Todos os mínimos']] as const).map(([id,label])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)}>{label}</button>)}</div>
 {lines.length?<div className="replenishment-scroll"><table><thead><tr>{['SKU '+company,'Produto','Apresentação','Atual (un.)','Mínimo (un.)','Repor (un.)','Kg','Observação'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{lines.map(r=><tr key={r.sku}><td><code>{r.sku}</code></td><td>{r.product}</td><td>{r.variation}</td><td>{r.current??'N/D'}</td><td>{r.minimum}</td><td><strong>{r.order??'Revisar'}</strong></td><td>{r.kg===null?'N/D':r.kg.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:6})}</td><td>{r.reason??(r.status==='ok'?'Mínimo atendido':'')}</td></tr>)}</tbody></table></div>:<p className="catalog-empty">{view==='order'?'Nenhum item com necessidade de reposição calculável. Confira os itens para revisão.':'Nenhum item nesta visualização.'}</p>}</>}
 </section>;
}
